# Generated by Django 4.1.7 on 2023-03-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcutegory",
            options={"ordering": ("position",)},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("is_visible", models.BooleanField(default=True)),
                ("is_cpecial", models.BooleanField(default=True)),
                ("is_signature", models.BooleanField(default=True)),
                ("disc", models.TextField(blank=True, max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("discount", models.PositiveSmallIntegerField(default=0)),
                ("ingradients", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="products")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.productcutegory",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
    ]
