# Generated by Django 4.2 on 2023-04-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_products_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("position", models.PositiveSmallIntegerField()),
                ("is_visible", models.BooleanField(default=True)),
                ("disc", models.TextField(blank=True, max_length=200)),
                ("photo", models.ImageField(upload_to="products")),
            ],
            options={
                "ordering": ("position",),
            },
        ),
    ]
